"""Command-line interface: the prototype the brief asks for in requirement E.

Six subcommands, each doing one thing:

    data        inspect the corpus that is available and how it was obtained
    train       fit the three layers and persist the detector
    detect      run detection on a chosen source and show explained alerts
    evaluate    the full metric suite, written to artifacts/evaluation.json
    scenarios   the five mandatory demonstration scenarios, in order
    dashboard   render the self-contained HTML analyst view
    all         train -> evaluate -> scenarios -> figures -> dashboard

Two deliberate properties. First, ``--source`` lets the user select the traffic data
(NSL-KDD if present, CICIDS2017 if present, the simulator otherwise, or a pcap file),
which is the "select traffic data" half of requirement E. Second, provenance is
printed on every run: if the corpus is simulated, the banner says so before any
number appears, so no output of this tool can be mistaken for a benchmark result.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np

from .config import (ALERT_DIR, ARTIFACT_DIR, FIGURE_DIR, MODEL_DIR, RANDOM_SEED,
                     SEVERITY_ORDER)
from .detect.explain import (alert_table_header, colour_enabled, format_alert,
                             format_alert_line)
from .detect.hybrid import HybridDetector

BANNER = r"""
 ___ ___ ___  ___
| \ | | |   \/ __|   hybrid network intrusion detection
|  \| | | |) \__ \   signature + supervised + anomaly, from scratch in NumPy
|_|\__|_|___/|___/
"""


# --------------------------------------------------------------------------- #
# Data loading
# --------------------------------------------------------------------------- #
def _load_source(args) -> tuple:
    """Resolve ``--source`` into (train, test, provenance)."""
    src = args.source
    if src == "pcap":
        from .data.pcap import load_pcap_as_frame
        if not args.pcap:
            sys.exit("--source pcap requires --pcap PATH")
        frame = load_pcap_as_frame(args.pcap, max_packets=args.max_packets)
        prov = {"source": "pcap", "name": os.path.basename(args.pcap),
                "note": ("Flows assembled from raw packets by nids/data/pcap.py. "
                         "There are no ground-truth labels, so detection can be "
                         "inspected but not scored."),
                "novel_in_test": []}
        return None, frame, prov
    if src == "cicids":
        from .data.cicids import load_cicids, stratified_train_test
        df, prov = load_cicids(max_rows_per_file=args.max_rows)
        train, test = stratified_train_test(df, seed=args.seed)
        return train, test, prov
    from .data.nsl_kdd import load_nsl_kdd
    # The simulator is seeded inside nids.data.simulate so that the synthetic corpus
    # is byte-identical run to run; there is deliberately no seed argument here.
    return load_nsl_kdd(force_simulated=(src == "simulated"),
                        n_train=args.max_rows)


def _provenance_banner(prov: dict, quiet: bool = False) -> None:
    if quiet:
        return
    name = prov.get("name", "?")
    print(f"\ncorpus    : {name}  [{prov.get('source')}]")
    if prov.get("note"):
        import textwrap
        print(textwrap.fill(prov["note"], 78, initial_indent="            ",
                            subsequent_indent="            ").lstrip())
    if prov.get("source") == "simulated":
        print("\n" + "!" * 78)
        print("!! SIMULATED CORPUS. Every number below is generated by")
        print("!! nids/data/simulate.py and is NOT an NSL-KDD benchmark result.")
        print("!! Put KDDTrain+.txt and KDDTest+.txt in data/raw/ and re-run.")
        print("!" * 78)


def _load_detector(path: str | None = None) -> HybridDetector:
    path = path or os.path.join(MODEL_DIR, "hybrid.pkl")
    if not os.path.exists(path):
        sys.exit(f"no fitted detector at {path}\n  run:  python -m nids train")
    return HybridDetector.load(path)


# --------------------------------------------------------------------------- #
# Subcommands
# --------------------------------------------------------------------------- #
def cmd_data(args) -> int:
    from .data import nsl_kdd
    from .data import cicids
    print(BANNER)
    print("Available traffic sources")
    print(f"  NSL-KDD files in data/raw/      : "
          f"{'PRESENT' if nsl_kdd.real_files_present() else 'absent'}")
    print(f"  CICIDS2017 CSVs in data/raw/    : "
          f"{'PRESENT' if cicids.files_present() else 'absent'}")
    pcaps = [f for f in os.listdir(os.path.join(ARTIFACT_DIR, "..", "data", "raw"))
             if f.endswith(".pcap")] if os.path.isdir(
                 os.path.join(ARTIFACT_DIR, "..", "data", "raw")) else []
    print(f"  pcap captures in data/raw/      : {', '.join(pcaps) or 'none'}")
    print("  built-in simulator              : ALWAYS available "
          "(nids/data/simulate.py)")

    train, test, prov = _load_source(args)
    _provenance_banner(prov, args.quiet)
    if train is not None:
        print(f"\ntrain rows: {len(train):,}")
        print(nsl_kdd.category_counts(train).to_string(index=False))
    print(f"\ntest rows : {len(test):,}")
    if "category" in test.columns:
        print(nsl_kdd.category_counts(test).to_string(index=False))
        print("\nper-family breakdown of the test split")
        print(nsl_kdd.family_counts(test).to_string(index=False))
    if train is not None and "label" in test.columns:
        tr = set(train["label"].astype(str))
        novel = sorted(set(test["label"].astype(str)) - tr - {"normal"})
        print(f"\nfamilies in test but never in train ({len(novel)}): "
              f"{', '.join(novel) or 'none'}")
        print("  These are the zero-day proxy. Scenario 5 is about them.")
    return 0


def cmd_train(args) -> int:
    print(BANNER)
    train, test, prov = _load_source(args)
    if train is None:
        sys.exit("cannot train on a pcap source: it has no labels")
    _provenance_banner(prov, args.quiet)
    print(f"\nfitting on {len(train):,} training connections")
    t0 = time.perf_counter()
    det = HybridDetector(seed=args.seed, n_trees=args.trees,
                         n_iforest=args.iforest).fit(train)
    print(f"  total fit time: {time.perf_counter() - t0:.1f}s")
    path = det.save(args.model)
    print(f"\nsaved detector -> {path}")
    with open(os.path.join(MODEL_DIR, "provenance.json"), "w",
              encoding="utf-8") as fh:
        json.dump(prov, fh, indent=2, default=str)
    return 0


def cmd_detect(args) -> int:
    print(BANNER)
    det = _load_detector(args.model)
    _, test, prov = _load_source(args)
    _provenance_banner(prov, args.quiet)

    print(f"\nrunning detection on {len(test):,} connections")
    result = det.predict(test)
    s = result.summary()
    print(f"  {s['alerts']:,} alerts ({s['alert_rate']:.2%} of connections) in "
          f"{s['timing']['total_s']:.2f}s "
          f"({s['timing']['rows_per_second']:,.0f} conn/s)")
    print(f"  by severity: " + ", ".join(f"{k}={v:,}" for k, v in
                                         sorted(s["by_severity"].items())))
    print(f"  by layer   : " + ", ".join(f"{k}={v:,}" for k, v in
                                        s["by_layer"].items()))

    floor = SEVERITY_ORDER.index(args.min_severity)
    keep = np.array([i for i in result.alert_rows.tolist()
                     if SEVERITY_ORDER.index(result.severity[i]) >= floor])
    if args.category:
        keep = np.array([i for i in keep.tolist()
                         if result.category[i] == args.category])
    if keep.size == 0:
        print(f"\nno alerts at severity >= {args.min_severity}"
              + (f" in category {args.category}" if args.category else ""))
        return 0

    colour = colour_enabled() and not args.no_colour
    recs = det.explain_alerts(test, result, rows=keep[:args.limit], limit=None)
    print(f"\ntop {len(recs)} of {keep.size:,} alerts at severity >= "
          f"{args.min_severity}, highest confidence first\n")
    print(alert_table_header())
    for r in recs:
        print(format_alert_line(r, colour))
    if not args.summary_only:
        print()
        for i, r in enumerate(recs[:args.detail], 1):
            print(format_alert(r, colour=colour, index=i, verbose=not args.brief))
            print()

    if args.json:
        # A bare filename ("queue.json") is a convenience: it lands in the alert
        # directory. Anything that looks like a path -- absolute, or containing a
        # separator -- is honoured as given, because silently reinterpreting
        # "artifacts/alerts/queue.json" as ALERT_DIR/artifacts/alerts/queue.json
        # produced a FileNotFoundError on a path the user had every reason to
        # expect to work.
        out = (args.json if os.path.isabs(args.json) or os.path.dirname(args.json)
               else os.path.join(ALERT_DIR, args.json))
        os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(recs, fh, indent=2, default=str)
        print(f"wrote {len(recs)} explained alerts -> {out}")
    return 0


def cmd_evaluate(args) -> int:
    from .evaluate import evaluate, print_summary, save_report
    print(BANNER)
    det = _load_detector(args.model)
    train, test, prov = _load_source(args)
    if train is None:
        sys.exit("cannot evaluate on an unlabelled pcap source")
    _provenance_banner(prov, args.quiet)
    report = evaluate(det, train, test, prov, n_examples=args.examples)
    print_summary(report)
    path = save_report(report, args.out)
    print(f"\nfull report -> {path}")

    print("\nPer-family recall (families absent from training marked *)")
    print(f"  {'family':<18} {'cat':<6} {'n':>6} {'hybrid':>7} {'sig':>7} "
          f"{'sup':>7} {'ano':>7}")
    for f in report["families"]:
        mark = " " if f["in_training"] else "*"
        print(f"  {mark}{f['family']:<17} {f['category']:<6} {f['support']:>6,} "
              f"{f['hybrid_recall']:>7.3f} {f['signature_recall']:>7.3f} "
              f"{f['supervised_recall']:>7.3f} {f['anomaly_recall']:>7.3f}")
    return 0


def cmd_scenarios(args) -> int:
    from .scenarios import print_scenario, run_scenarios, save_scenarios
    print(BANNER)
    det = _load_detector(args.model)
    train, test, prov = _load_source(args)
    if train is None:
        sys.exit("the scenarios need labelled data; use --source nsl-kdd or simulated")
    _provenance_banner(prov, args.quiet)

    result = det.predict(test)
    truth = (test["category"].astype(str) != "normal").to_numpy()
    pcap = args.pcap or os.path.join(os.path.dirname(ARTIFACT_DIR), "data", "raw",
                                     "demo_capture.pcap")
    scs = run_scenarios(det, test, result, truth,
                        novel=set(prov.get("novel_in_test", [])),
                        pcap_path=None if args.no_pcap else pcap)
    wanted = set(args.only) if args.only else None
    colour = colour_enabled() and not args.no_colour
    for sc in scs:
        if wanted and sc["id"] not in wanted:
            continue
        print_scenario(sc, colour=colour, examples=args.examples,
                       verbose=not args.brief)
    path = save_scenarios(scs, args.out)
    print(f"\nscenario data -> {path}")
    return 0


def cmd_dashboard(args) -> int:
    from .evaluate import queue_sample
    from .report import figures
    from .report.html import build_dashboard
    print(BANNER)

    rep_path = args.report or os.path.join(ARTIFACT_DIR, "evaluation.json")
    scn_path = args.scenarios or os.path.join(ARTIFACT_DIR, "scenarios.json")
    if not os.path.exists(rep_path):
        sys.exit(f"no evaluation report at {rep_path}\n"
                 f"  run:  python -m nids evaluate")
    with open(rep_path, encoding="utf-8") as fh:
        report = json.load(fh)
    scenarios = []
    if os.path.exists(scn_path):
        with open(scn_path, encoding="utf-8") as fh:
            scenarios = json.load(fh)

    if not args.no_figures:
        print("drawing figures")
        figures.build_all(report, scenarios, FIGURE_DIR)

    det = _load_detector(args.model)
    _, test, prov = _load_source(args)
    result = det.predict(test)
    truth = ((test["category"].astype(str) != "normal").to_numpy()
             if "category" in test.columns else None)
    rows = queue_sample(result, truth, top=args.top, seed=args.seed)
    print(f"explaining {rows.size} alerts for the queue view")
    alerts = det.explain_alerts(test, result, rows=rows, limit=None)

    out = build_dashboard(report, scenarios, alerts, FIGURE_DIR, args.out)
    size = os.path.getsize(out) / 1e6
    print(f"\ndashboard -> {out}  ({size:.1f} MB, self-contained)")
    print("  open it directly in a browser; it needs no server and no network")
    return 0


def cmd_all(args) -> int:
    """train -> evaluate -> scenarios -> figures -> dashboard, in one run."""
    for name, fn in (("train", cmd_train), ("evaluate", cmd_evaluate),
                     ("scenarios", cmd_scenarios), ("dashboard", cmd_dashboard)):
        print("\n" + "#" * 78)
        print(f"# {name}")
        print("#" * 78)
        rc = fn(args)
        if rc:
            return rc
    print("\n" + "=" * 78)
    print("Everything regenerated. Artefacts:")
    for p in ("evaluation.json", "scenarios.json", "dashboard.html"):
        f = os.path.join(ARTIFACT_DIR, p)
        if os.path.exists(f):
            print(f"  {f}  ({os.path.getsize(f) / 1e3:,.0f} kB)")
    print(f"  {FIGURE_DIR}/  ({len([f for f in os.listdir(FIGURE_DIR)])} figures)")
    return 0


# --------------------------------------------------------------------------- #
# Argument parsing
# --------------------------------------------------------------------------- #
def _add_common(p: argparse.ArgumentParser) -> None:
    p.add_argument("--source", default="nsl-kdd",
                   choices=["nsl-kdd", "simulated", "cicids", "pcap"],
                   help="which traffic data to use (default: nsl-kdd, which falls "
                        "back to the simulator if the files are absent)")
    p.add_argument("--pcap", help="path to a .pcap file (with --source pcap)")
    p.add_argument("--max-packets", type=int, default=None,
                   help="cap packets read from a pcap")
    p.add_argument("--max-rows", type=int, default=None,
                   help="cap rows loaded from the corpus")
    p.add_argument("--model", default=None,
                   help="detector path (default artifacts/models/hybrid.pkl)")
    p.add_argument("--seed", type=int, default=RANDOM_SEED)
    p.add_argument("--quiet", action="store_true",
                   help="suppress the provenance banner")
    p.add_argument("--no-colour", action="store_true", help="disable ANSI colour")


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="python -m nids",
        description="Hybrid network intrusion detection: signature rules, a "
                    "supervised random forest and an isolation-forest anomaly "
                    "layer, fused into one explained alert queue.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="typical first run:\n"
               "  python -m nids all\n"
               "  open artifacts/dashboard.html\n")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("data", help="show which corpora are available and their mix")
    _add_common(p)
    p.set_defaults(fn=cmd_data)

    p = sub.add_parser("train", help="fit the three layers and save the detector")
    _add_common(p)
    p.add_argument("--trees", type=int, default=120,
                   help="trees in the supervised forest (default 120)")
    p.add_argument("--iforest", type=int, default=150,
                   help="trees in the isolation forest (default 150)")
    p.set_defaults(fn=cmd_train)

    p = sub.add_parser("detect", help="run detection and show explained alerts")
    _add_common(p)
    p.add_argument("--limit", type=int, default=25,
                   help="alerts to list (default 25)")
    p.add_argument("--detail", type=int, default=3,
                   help="alerts to expand in full (default 3)")
    p.add_argument("--min-severity", default="low", choices=SEVERITY_ORDER,
                   help="hide alerts below this severity (default low)")
    p.add_argument("--category", help="only this attack category")
    p.add_argument("--brief", action="store_true",
                   help="omit per-feature evidence from expanded alerts")
    p.add_argument("--summary-only", action="store_true",
                   help="one line per alert, no expansion")
    p.add_argument("--json", help="also write the explained alerts to this file")
    p.set_defaults(fn=cmd_detect)

    p = sub.add_parser("evaluate", help="full metric suite -> evaluation.json")
    _add_common(p)
    p.add_argument("--examples", type=int, default=3,
                   help="TP/FP/FN examples to extract (default 3)")
    p.add_argument("--out", default=None)
    p.set_defaults(fn=cmd_evaluate)

    p = sub.add_parser("scenarios", help="the five mandatory demonstrations")
    _add_common(p)
    p.add_argument("--only", type=int, nargs="+",
                   help="run only these scenario ids, e.g. --only 2 3")
    p.add_argument("--examples", type=int, default=1,
                   help="explained alerts to show per scenario (default 1)")
    p.add_argument("--brief", action="store_true")
    p.add_argument("--no-pcap", action="store_true",
                   help="skip the raw-capture scenario")
    p.add_argument("--out", default=None)
    p.set_defaults(fn=cmd_scenarios)

    p = sub.add_parser("dashboard", help="render the self-contained HTML view")
    _add_common(p)
    p.add_argument("--report", default=None)
    p.add_argument("--scenarios", default=None)
    p.add_argument("--top", type=int, default=200,
                   help="alerts from the head of the queue to embed (default 200); "
                        "a stratified sample of every severity band and of the "
                        "highest-confidence false positives is added to it")
    p.add_argument("--no-figures", action="store_true",
                   help="reuse the figures already in artifacts/figures")
    p.add_argument("--out", default=None)
    p.set_defaults(fn=cmd_dashboard)

    p = sub.add_parser("all", help="train, evaluate, scenarios, figures, dashboard")
    _add_common(p)
    p.add_argument("--trees", type=int, default=120)
    p.add_argument("--iforest", type=int, default=150)
    p.add_argument("--examples", type=int, default=3)
    p.add_argument("--only", type=int, nargs="+", default=None)
    p.add_argument("--brief", action="store_true")
    p.add_argument("--no-pcap", action="store_true")
    p.add_argument("--no-figures", action="store_true")
    p.add_argument("--report", default=None)
    p.add_argument("--scenarios", default=None)
    p.add_argument("--top", type=int, default=200)
    p.add_argument("--out", default=None)
    p.set_defaults(fn=cmd_all)
    return ap


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    # 'all' shares one namespace across subcommands whose --out mean different
    # things, so it must not forward a single --out to all of them.
    if args.fn is cmd_all:
        args.out = None
    return args.fn(args)


if __name__ == "__main__":                                    # pragma: no cover
    raise SystemExit(main())
